# mkdocs is used to build the documentation at docs.retrotxt.com
# these are built using a GitHub Action the HTML is stored in
# the `gh-pages` branch
#
# to view this documentation locally requires the mkdocs tool
# https://www.mkdocs.org/getting-started/#installation
#
# mkdocs requires Python3 and pip
#
# pip install mkdocs
# pip install mkdocs-material-extensions
# pip install mkdocs_pymdownx_material_extras
#
# mkdocs serve
# mkdocs build

site_name: RetroTxt
copyright: RetroTxt &copy; 2022-24 Ben Garrett
repo_url: https://github.com/bengarrett/RetroTxt

theme:
  name: material
  language: en
  logo: assets/retrotxt_128.svg
  favicon: assets/retrotxt_128.svg
  palette:
    primary: teal
    accent: indigo
  font:
    code: IBM Plex Mono
  features:
    - content.code.copy
nav:
  - Install: index.md
  - Usage:
      - First-time usage: usage/first.md
      - Secure RetroTxt: usage/secure.md
      - View local files: usage/local.md
      - Suggestions: usage/websites.md
      - Garbled text: usage/garbled.md
      - Font size: usage/font_size.md
      - Font rendering: usage/pref.md
      - Commands: usage/omnibar.md
  - Limitations: limitations.md
  - Supported standards:
      - Control sequences: specs/controls.md
      - Codepages: specs/cp.md
      - ANSI / ECMA-48: specs/ansi.md
      - ANSI.SYS: specs/ansi_sys.md
      - BBS colors: specs/bbs.md
      - Non-standard: specs/misc.md
      - SAUCE (metadata): specs/sauce.md
  - Source code:
      - Manifest V3: src/mv3.md
      - Program patterns: src/pattern.md
      - Libraries in use: src/library.md
      - Standards: src/standard.md
      - Files & directories: src/files.md
      - Fonts: src/font.md
      - Install & usage: src/index.md
      - Tips for building: src/build.md
  - Changes: changes.md
  - Hosting on the web:
      - Nginx: host/nginx.md
  - Policies:
      - Privacy: privacy.md
      - Security: https://github.com/bengarrett/RetroTxt/blob/main/.github/SECURITY.md
      - Code of conduct: https://github.com/bengarrett/RetroTxt/blob/main/.github/CODE_OF_CONDUCT.md
      - Contributing: https://github.com/bengarrett/RetroTxt/blob/main/.github/CONTRIBUTING.md
      - License: https://github.com/bengarrett/RetroTxt/blob/main/LICENSE

plugins:
  - search

markdown_extensions:
  # Python Markdown
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Icons + Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # Footnote
  - footnotes
