version: "3"
# This task runner requires Task to be installed.
# https://taskfile.dev/#/installation
#
# `task` is a Go terminal application that runs in the RetroTxt root directory
#
# Rules
# manifest.json is always a copy of manifest_chrome except when running Firefox specific tasks
# some tasks require the use of yarn https://yarnpkg.com/en/docs/install
#
# Tasks do not run on PowerShell, Windows users should use WSL.
#

vars:
  # The published version number of RetroTxt used in the manifest.json and GitHub commit
  # Must use the numeric format 5.0.0
  VERSION: "5.0.0"

tasks:
  # internal commands
  copy-manifest:
    cmds:
      - cp -f "{{.SRC}}" "ext/manifest.json"
    silent: true
  init-firefox:
    cmds:
      - task: copy-manifest
        vars: { SRC: "ext/json/manifest_firefox.json" }
  init-chrome:
    cmds:
      - task: copy-manifest
        vars: { SRC: "ext/json/manifest_chrome.json" }
  rename-build:
    dir: web-ext-artifacts
    cmds:
      - mv -f "retrotxt-{{.VERSION}}.zip" "retrotxt_for_{{.BROWSER}}-{{.VERSION}}.zip"
    status:
      - test -f "retrotxt_for_{{.BROWSER}}-{{.VERSION}}.zip"
  set-ver-chrome:
    cmds:
      - yarn run dot-json ext/json/manifest_chrome.json version "{{.VERSION}}"
    silent: true
  set-ver-firefox:
    cmds:
      - yarn run dot-json ext/json/manifest_firefox.json version "{{.VERSION}}"
    silent: true
  set-ver-npm:
    cmds:
      - yarn version --new-version "{{.VERSION}}"
      - cmd: git tag "v{{.VERSION}}"
        ignore_error: true
      - cmd: git push --tags
        ignore_error: true
    silent: true

  # user commands that are displayed with `task --list`
  builds:
    desc: Creates submission packages for both Chrome and Firefox add-ons.
    cmds:
      - task: build-chrome
      - task: build-firefox
  build-chrome:
    # edit web-ext-chrome.js to hide files and directories
    desc: Creates a package that is intended for submission to the Chrome Web Store.
    summary: |
      Creates a package that is intended for submission to the Chrome Web Store.

      Packaged file will be located in /web-ext-artifacts
      Its filename will be retrotxt_for_chrome-{{.VERSION}}.zip
    cmds:
      - task: version-set
      - task: init-chrome
      - task: depends
      - cmd: yarn run web-ext --config ext/.web-ext-chrome.js --source-dir ./ext build
        ignore_error: true
      - task: rename-build
        vars: { BROWSER: "chrome" }
        ignore_error: true
  build-firefox:
    # edit web-ext-config.js to hide files and directories
    desc: Creates a package that is intended for submission to Firefox Add-ons.
    summary: |
      Creates a package that is intended for submission to the Firefox Add-ons website.

      Packaged file will be located in /web-ext-artifacts
      Its filename will be retrotxt_for_firefox-{{.VERSION}}.zip
    cmds:
      - task: version-set
      - task: init-firefox
      - task: depends
      - cmd: yarn run web-ext --config ext/.web-ext-firefox.js --source-dir ./ext build
        ignore_error: true
      - task: rename-build
        vars: { BROWSER: "firefox" }
        ignore_error: true
      - task: init-chrome
  depends:
    desc: Copies the latest yarn dependencies over to the package.
    cmds:
      #- cmd: cp -f "node_modules/bulma/css/bulma.css" "ext/css/bulma.css"
      - cmd: cp -f "node_modules/bulma/css/bulma.min.css" "ext/css/bulma.min.css"
      - cmd: cp -f "node_modules/qunit/qunit/qunit.css" "ext/test/qunit.css"
      - cmd: cp -f "node_modules/qunit/qunit/qunit.js" "ext/test/qunit.js"
  lint:
    desc: Lints this codebase against Mozilla's Extension specifications.
    cmds:
      - task: init-firefox
      - cmd: yarn run --silent web-ext --config ext/.web-ext-firefox.js --source-dir ./ext --version
      - cmd: yarn run --silent web-ext --config ext/.web-ext-firefox.js --source-dir ./ext lint
        ignore_error: true
      - task: init-chrome
  init:
    desc: Initialises this repository for first time use after being cloned.
    cmds:
      - task: init-chrome
      - cmd: yarn install
      - task: depends
  # serve-chrome:
  # Chrome does not have a command line switch to enable the reloading of an Extension
  serve-firefox:
    desc: Launches Firefox with the codebase in this active directory.
    cmds:
      - task: init-firefox
      - cmd: printf "\n\e[33mPlease always quit Firefox from its program menu\e[0m\n\n"
        silent: true
      - cmd: yarn run web-ext --config ext/.web-ext-firefox.js --source-dir ./ext run
        silent: true
        ignore_error: true
      - task: init-chrome
  version-set:
    desc: Applies the VERSION in Taskfile.yml variable value to the manifest.json and package.json files.
    deps: [set-ver-chrome, set-ver-firefox, set-ver-npm]
    cmds:
      - task: init-chrome
  version-purge:
    desc: Removes the current VERSION variable value as a tag from the GitHub repository.
    cmds:
      - cmd: git tag "v{{.VERSION}}" --delete
        ignore_error: true
      - cmd: git push --tags
  commit:
    desc: Applies the VERSION variable to the JSON files and commits it to GitHub.
    deps: [set-ver-chrome, set-ver-firefox, version-purge, builds]
    cmds:
      - task: version-purge
        ignore_error: true
      - task: set-ver-chrome
      - task: set-ver-firefox
      - task: builds
      - cmd: git tag -a "v{{.VERSION}}" --message "Version {{.VERSION}}"
      - cmd: git push --tags
      - cmd: git push
