# Task runner for Manifest V3 for Chromium browsers
# =================================================
# As of Aug. 2022 Firefox is not supported.
#
# This task runner requires Task to be installed.
# https://taskfile.dev/#/installation
#
version: "3"

silent: true

vars:
  REQDOCS: "task requires the installation of mkdocs: https://www.mkdocs.org/user-guide/installation"
  REQPNPM: "task requires the installation of pnpm: https://pnpm.io/installation"
  REQSHX: "task requires the installation of shelljs/shx: https://github.com/shelljs/shx"
  REQWEXT: "task requires the installation of Web-ext: https://github.com/mozilla/web-ext"
  REQMAT: "task requires the installation of Material for MkDocs: https://squidfunk.github.io/mkdocs-material"

tasks:
  default:
    desc: List the available tasks.
    cmds:
     - task --list

  lint:
    desc: Lint the JavaScript files in the `ext` directory.
    ignore_error: true
    cmds:
      - cmd: echo 'Running ESLint on extension scripts...'
      # node and dependencies
      - cmd: pnpm exec eslint ext/scripts/sw/*.js --stats
      - cmd: pnpm exec eslint ext/scripts/*.js --stats

  lint:security:
    desc: Run security linting with ESLint security plugins.
    ignore_error: true
    cmds:
      - cmd: echo 'Running security linting on extension scripts...'
      - cmd: cd ext && node security-lint.js

  lint:security:ci:
    desc: Run security linting in CI mode (strict, fails on issues).
    cmds:
      - cmd: echo 'Running security linting in CI mode...'
      - cmd: cd ext && node security-lint.js
      - cmd: test $? -eq 0 || (echo 'Security linting failed - vulnerabilities detected' && exit 1)

  lint:all:
    desc: Run both regular linting and security linting.
    ignore_error: true
    cmds:
      - task: lint
      - task: lint:security

  lint:all:ci:
    desc: Run both regular and security linting in CI mode (strict).
    cmds:
      - task: lint
      - task: lint:security:ci

  coverage:
    desc: Generate code coverage summary report.
    cmds:
      - cmd: echo 'Generating code coverage summary...'
      - cmd: cd ext && node coverage-summary.js

  coverage:ci:
    desc: Generate code coverage summary in CI mode (strict).
    cmds:
      - cmd: echo 'Generating code coverage summary in CI mode...'
      - cmd: cd ext && node coverage-summary.js
      - cmd: test -f ext/coverage/summary.json || (echo 'Coverage summary generation failed' && exit 1)

  benchmark:
    desc: Run performance benchmarks.
    cmds:
      - cmd: echo 'Running performance benchmarks...'
      - cmd: cd ext && node benchmark.js

  benchmark:ci:
    desc: Run performance benchmarks in CI mode (strict).
    cmds:
      - cmd: echo 'Running performance benchmarks in CI mode...'
      - cmd: cd ext && node benchmark.js
      - cmd: test -f ext/benchmarks/benchmark-*.json || (echo 'Benchmark generation failed' && exit 1)

  benchmark:expanded:
    desc: Run expanded performance benchmarks.
    cmds:
      - cmd: echo 'Running expanded performance benchmarks...'
      - cmd: cd ext && node benchmark-expanded.js

  benchmark:expanded:ci:
    desc: Run expanded performance benchmarks in CI mode (strict).
    cmds:
      - cmd: echo 'Running expanded performance benchmarks in CI mode...'
      - cmd: cd ext && node benchmark-expanded.js
      - cmd: test -f ext/benchmarks/benchmark-expanded-*.json || (echo 'Expanded benchmark generation failed' && exit 1)

  benchmark:error:
    desc: Run error handling benchmarks.
    cmds:
      - cmd: echo 'Running error handling benchmarks...'
      - cmd: cd ext && node benchmark-error-handling.js

  benchmark:error:ci:
    desc: Run error handling benchmarks in CI mode (strict).
    cmds:
      - cmd: echo 'Running error handling benchmarks in CI mode...'
      - cmd: cd ext && node benchmark-error-handling.js
      - cmd: test -f ext/benchmarks/error-handling-*.json || (echo 'Error handling benchmark generation failed' && exit 1)

  # user commands that are displayed with `task --list`
  build:
    desc: Creates the submission package for Chrome.
    summary: |
      Creates a package that is intended for submission to the Chrome Web Store
      and Microsoft Edge Add-ons.

      Packaged file will be located in /web-ext-artifacts
    cmds:
      - task: build-chrome

  build-chrome:
    # edit web-ext-chrome.js to hide files and directories
    preconditions:
      - sh: pnpm -v
        msg: "{{.REQPNPM}}"
      - sh: pnpm exec web-ext --version
        msg: "{{.REQWEXT}}"
    cmds:
      - task: dep-copy
      - cmd: pnpm exec web-ext --config ext/.web-ext-chrome.js --source-dir ./ext build
        ignore_error: true

  checks:
    desc: Check, run and print the versions of the task commands and dependencies.
    ignore_error: true
    cmds:
      # node and dependencies
      - cmd: pnpm exec shx echo -n "Node.js "
      - cmd: node --version
      - cmd: pnpm exec shx echo -n "pnpm version "
      - cmd: pnpm --version
      - cmd: pnpm exec shx --version
      - cmd: pnpm exec shx echo -n "Web-ext v"
      - cmd: pnpm exec web-ext --version
      # python and dependencies
      - cmd: python --version
      - cmd: mkdocs --version
      - cmd: pip --version
      - cmd: pip show mkdocs-material --quiet
      # system tools
      - cmd: pnpm exec shx echo ""
      - cmd: git --version
      - cmd: task --version

  dep-copy:
    desc: Copies the dependencies from `node_modules` over to the `ext` directory.
    preconditions:
      - sh: pnpm -v
        msg: "{{.REQPNPM}}"
      - sh: pnpm exec shx --version
        msg: "{{.REQSHX}}"
    # use shx for Windows compatibility
    cmds:
      - cmd: pnpm exec shx cp -f "node_modules/bulma/css/bulma.min.css" "ext/css/bulma.min.css"
      - cmd: pnpm exec shx cp -f "node_modules/qunit/qunit/qunit.css" "ext/test/qunit.css"
      - cmd: pnpm exec shx cp -f "node_modules/qunit/qunit/qunit.js" "ext/test/qunit.js"
      - cmd: pnpm exec shx cp -f "node_modules/linkifyjs/dist/linkify.js" "ext/js/linkify.js"
      - cmd: pnpm exec shx cp -f "node_modules/linkify-plugin-ip/dist/linkify-plugin-ip.js" "ext/js/linkify-plugin-ip.js"
      - cmd: pnpm exec shx cp -f "node_modules/linkify-element/dist/linkify-element.js" "ext/js/linkify-element.js"
      - cmd: pnpm exec shx cp -f "node_modules/dompurify/dist/purify.js" "ext/js/purify.js"

  dep-install:
    desc: Installs both the dependencies and dev-dependencies contained in the package.json.
    preconditions:
      - sh: pnpm -v
        msg: "{{.REQPNPM}}"
    cmds:
      - cmd: pnpm install
      - task: dep-copy

  dep-update:
    desc: Updates all dependencies to the latest version and copies them to the `ext` directory.
    preconditions:
      - sh: pnpm -v
        msg: "{{.REQPNPM}}"
      - sh: pnpm exec shx --version
        msg: "{{.REQSHX}}"
    cmds:
      - cmd: pnpm update
      - cmd: pnpm exec shx echo ""
      - task: dep-copy

  dep-latest:
    desc: Interactively update to the latest dependencies and copy them to the `ext` directory.
    preconditions:
      - sh: pnpm -v
        msg: "{{.REQPNPM}}"
      - sh: pnpm exec shx --version
        msg: "{{.REQSHX}}"
    cmds:
      - cmd: pnpm update --interactive --latest
      - cmd: pnpm exec shx echo ""
      - task: dep-copy

  test:
    desc: Run QUnit tests in headless Chrome using Puppeteer, however this will return failed tests.
    cmds:
      - cmd: node run-qunit.js

  test-extension:
    desc: Run QUnit tests in a real Chrome WebExtension context using Puppeteer.
    cmds:
      - cmd: node run-qunit-extension.js

  test-install:
    desc: Download the required Chrome browser for Puppeteer.
    cmds:
      - cmd: pnpm exec puppeteer browsers install chrome

  test-uninstall:
    desc: Remove the downloaded Chrome browser for Puppeteer.
    cmds:
      - cmd: rm -rf ~/.cache/puppeteer

  docs-build:
    desc:  Build the current documentation in use on https://docs.retrotxt.com.
    preconditions:
      - sh: pip show mkdocs-material
        msg: "{{.REQMAT}}"
      - sh: pnpm -v
        msg: "{{.REQPNPM}}"
      - sh: pnpm mkdocs -V
        msg: "{{.REQDOCS}}"
    cmds:
      - cmd: pnpm mkdocs build

  docs-install:
    desc: Install required Python packages for documentation (mkdocs, mkdocs-material).
    cmds:
      - cmd: pip install mkdocs mkdocs-material

  docs-serve:
    desc:  Run an internal server to view the documentation in `docs`.
    preconditions:
      # - sh: pip show mkdocs-material
      #   msg: "{{.REQMAT}}"
      - sh: pnpm -v
        msg: "{{.REQPNPM}}"
      - sh: pnpm mkdocs -V
        msg: "{{.REQDOCS}}"
    cmds:
      - cmd: pnpm mkdocs serve
        ignore_error: true # ignore Ctrl-C exit interrupts
