
|16    |00Black            |23 Black      
|16    |04Red              |23 Red        
|16    |02Green            |23 Green      
|16    |06Yellow           |23 Yellow     
|16    |01Blue             |23 Blue       
|16    |05Magenta          |23 Magenta    
|16    |03Cyan             |23 Cyan       
|16    |07White            |23 White      
|16    |08Bright Black     |23 B. Black   
|16    |12Bright Red       |23 B. Red     
|16    |10Bright Green     |23 B. Green   
|16    |14Bright Yellow    |23 B. Yellow  
|16    |09Bright Blue      |23 B. Blue    
|16    |13Bright Magenta   |23 B. Magenta 
|16    |11Bright Cyan      |23 B. Cyan    
|16    |15Bright White     |23 B. White   

|16    |23 |00ÚÄÄÄÄÄÄÄÄÄÄÄÄÄ¿ 
|16    |23 ³ Hello |23world|23 ³ 
|16    |23 ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÙ 
